manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmk_encoder
      url-base: https://github.com/abababababababa

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: zmk_encoder
      remote: zmk_encoder
      revision: main
      path: modules/zmk_encoder
      import: false

  self:
    path: config